
services:
  nginx:
    build: ./requirements/nginx
    image: inception-nginx
    ports:
      - "8080:443" # Mapea el puerto 443 de mi host para redirigirlo al 443 del container
    volumes: # Defines persistant storage
      - ./requirements/nginx/conf/ssl:/etc/nginx/ssl 
      - ./requirements/nginx/conf:/etc/nginx
    networks:
      - my_network

  mariadb:
      build:
        #context: ../..
        dockerfile: srcs/requirements/mariadb/Dockerfile
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      image: inception-mariadb
      volumes:
        - db_data:/var/lib/mysql
      ports:
        - "3306:3306"
      networks:
        - my_network


# De forma predeterminada se crea un espacio de nombres de red personalizado con el
# controlador Bridge que crea una red interna con una ip única por contenedor.
networks:
  my_network:
    driver: bridge
  
volumes:
  db_data: