
services:
  nginx:
    build: ./requirements/nginx
    image: inception-nginx
    ports:
      - "8080:443" # Mapea el puerto 443 de mi host para redirigirlo al 443 del container
    volumes: # Defines persistant storage
      - ./requirements/nginx/conf/ssl:/etc/nginx/ssl 
      - ./requirements/nginx/conf:/etc/nginx
    networks:
      - my_network

  mariadb:
      build: ./requirements/mariadb
      image: inception-mariadb
      volumes:
        - mariadb_data:/var/lib/mysql
        - ./requirements/mariadb/tools/db1.sql:/docker-entrypoint-initdb.d/db1.sql  # Montar el script
      networks:
      - my_network
      command: ["mysqld_safe"]  # Mantener el contenedor corriendo


# De forma predeterminada se crea un espacio de nombres de red personalizado con el
# controlador Bridge que crea una red interna con una ip única por contenedor.
networks:
  my_network:
    driver: bridge
  
volumes:
  mariadb_data: